title: Layer 8 Security 
description: "Another Security Blog"
author:
  name: "Layer8Security"
  email: "security@layer8.pe"
  url: "https://layer8sec.github.io/blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Layer 8 Security"
year : "2021"
